# Generated by Django 4.2.6 on 2023-10-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_product_updated_at_product_user_wishlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(default='images/the_art_of_war.jpg', upload_to='images/'),
        ),
    ]
