# Generated by Django 4.2.6 on 2023-10-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='reviewer_email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='reviewer_name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
