# Generated by Django 4.2.6 on 2023-10-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_productreview_reviewer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='reviewer_email',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='reviewer_name',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_text',
            field=models.TextField(verbose_name='Review'),
        ),
    ]
