# Generated by Django 4.2.6 on 2023-10-29 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_remove_productreview_reviewer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ('-created',), 'verbose_name': 'Product Review', 'verbose_name_plural': 'Product Reviews'},
        ),
    ]
