# Generated by Django 4.2.6 on 2023-10-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_productreview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='review_profile',
            field=models.ImageField(default='images/default_user.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='reviewer_email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='reviewer_name',
            field=models.CharField(default='user', max_length=255, verbose_name='Name'),
        ),
    ]
