# Generated by Django 4.2.6 on 2023-11-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_productimage_crop_coordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='crop_coordinates',
        ),
        migrations.AddField(
            model_name='productimage',
            name='crop_x',
            field=models.FloatField(blank=True, null=True, verbose_name='X Coordinate'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='crop_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Y Coordinate'),
        ),
    ]
