# Generated by Django 4.2.6 on 2023-11-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_remove_productimage_cropped_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='crop_x',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='crop_y',
        ),
        migrations.AddField(
            model_name='productimage',
            name='crop_left',
            field=models.FloatField(blank=True, null=True, verbose_name='Left Coordinate'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='crop_lower',
            field=models.FloatField(blank=True, null=True, verbose_name='Lower Coordinate'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='crop_right',
            field=models.FloatField(blank=True, null=True, verbose_name='Right Coordinate'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='crop_upper',
            field=models.FloatField(blank=True, null=True, verbose_name='Upper Coordinate'),
        ),
    ]
