# Generated by Django 4.2.6 on 2023-11-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_remove_productimage_crop_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='crop_left',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Left Coordinate'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='crop_lower',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Lower Coordinate'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='crop_right',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Right Coordinate'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='crop_upper',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Upper Coordinate'),
        ),
    ]
