# Generated by Django 4.2.6 on 2023-11-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_category_discount_category_on_sale_categoryoffers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='discount',
        ),
    ]
