# Generated by Django 4.2.6 on 2023-11-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_alter_productoffer_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='edited',
        ),
        migrations.AddField(
            model_name='productreview',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
