# Generated by Django 4.2.6 on 2023-11-21 11:40

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_remove_productreview_edited_productreview_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10, verbose_name='Discount Price'),
        ),
    ]
