# Generated by Django 4.2.6 on 2023-11-21 06:16

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_created_at_referral_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='activation_link_expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 6, 17, 5, 193013, tzinfo=datetime.timezone.utc)),
        ),
    ]
