# Generated by Django 4.2.6 on 2023-11-21 06:17

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_activation_link_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activation_link_expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 6, 17, 47, 234302, tzinfo=datetime.timezone.utc)),
        ),
    ]
