# Generated by Django 4.2.6 on 2023-11-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CroppedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='cropped_images/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
