# Generated by Django 4.2.6 on 2023-11-09 16:20

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_coupon_active_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 16, 20, 48, 468169, tzinfo=datetime.timezone.utc)),
        ),
    ]
