# Generated by Django 4.2.6 on 2023-11-09 16:21

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 16, 21, 12, 114604, tzinfo=datetime.timezone.utc)),
        ),
    ]
