# Generated by Django 4.2.6 on 2023-11-10 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(),
        ),
    ]
