# Generated by Django 4.2.6 on 2023-11-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw'), ('Purchase', 'Purchase'), ('Return', 'Return'), ('Referel', 'Referel')], max_length=10),
        ),
    ]
