# Generated by Django 4.2.6 on 2023-10-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_post_code_order_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod_payment',
            field=models.BooleanField(default=False),
        ),
    ]
