# Generated by Django 4.2.6 on 2023-11-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Requested', 'Requested'), ('Returned', 'Returned')], default='Pending', max_length=255),
        ),
    ]
