# Generated by Django 4.2.6 on 2023-11-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreturn',
            name='screenshot',
            field=models.ImageField(blank=True, upload_to='images/return_screenshots/'),
        ),
    ]
