# Generated by Django 4.2.6 on 2023-11-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderreturn_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreturn',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
